version: '3'
services:

  bash:
    image: node:9.8.0
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - PATH=/code/node_modules/.bin/:$PATH
    command: "sh"

  web:
    image: node:9.8.0
    ports:
      - "80:80"
    working_dir: "/code"
    volumes:
      - .:/code
    environment:
      - PATH=/code/node_modules/.bin/:$PATH
    command: "reload -b -p 80"

  watch:
    image: node:9.8.0
    working_dir: "/code"
    volumes:
      - .:/code
    environment:
      - PATH=/code/node_modules/.bin:$PATH
    command: "webpack --config webpack.development.js -w --mode development"

